theme: jekyll-theme-hacker
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Social Media CRUD App Basic]
description: The application will allow you to add post on your computer, read, update them on website and delete them. Its mainly a CRUD app. CRUD is a type of mechanism that allows you to create data, read data, edit it, and delete those data.
